language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t akkien/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akkien/docker-react npm run test
