language: generic
sudo: required
services:
- docker
addons:
  sshknownhosts:
  - 128.199.90.27
branches:
  only:
  - master
env:
  global:
  - DOCKER_IMAGE=akkien/docker-react
  - REMOTE_USER=deployer
  - REMOTE_HOST=128.199.90.27
  - secure: PF6RReuNVxEorBRCba1TNyRn0wWR2+x7MWB6A8tzsRzKB+s5htLktEqvNxwxU5yT3LrJFEvYEcbJNLMuFxTux7byO79gXI1vWoCHrzcXGeo8nu2d6UvJuj/iE15XmoKStye73cbQdTDD+b5CrDtVgLaEfZrqMAtAxDU5SjoT/dq2vC3iyq3J89PVYiou+96mPV2iTDPshfKzXNY/H2Lw2ac04e8jR8H3/P0hqH+A4eRSh+JBX11KcmCo6nXZL5tIyRP12/gTgYcbjLbhxXaOO0Jt7cDWetpEaKN/sKajQbHojflyPjREl4H3JX5cfx2+45uA3JnoE5zdBe5ONKA4goU1GIxKvqbgLlR8lzabeNzvgVJ47j3GnYIeGj28WIR6Yi19zb1CnHOyNyGe6j+cNr8erqOLPbKa1d/sC+9WoJlXCiz4MYBY7Wuxat/jATIt3TeGvlmEl+AocHqzMKkNvbWNi2sloraVmp0injfrOTe7yi34pME7CQxxwswsNvVU1iBPm39l1J1H44Apmc9FbfWvVcFP9MUxNc6R87N01lehkf6NVFO0sl9MtNr4Q/GKjHtGwd3JJ+4gTOFXz2LlGvFIKdhb6Xw+ttyHuN2T6YUej9S03s3e6J2f9Lp8On5asHfacPTa39aL4nndo5NhVEr+jKZglBoov9/SJsXeR+k=
  - secure: ZMjFT+ym8o+P4Mgz319ikcSk5JdGac5DfcvlmLj/Zswgu6VYOy26HuLvSUSl8bTcFi+njjKzte/UCmJdf27NV22nmTx0jI2wNJhZIdvhtRiIiqcNKLmeyHknrMlXAYTWN6Ew3jP810BT+9OYmaNj8jJQAdZfmDvVvpGx2nFbFxYXtb1qYx4j5vz2gSMqoQuHayhTU+JYT929vX28dIcKfVpoAiVfi3zrlqceu5jHeNCP6/nuNyrZtShxZnd5inrRrGOVanh9RyxUc1Dr8+bVNYG0GGM51WF+83WRzrLYfts1XlC8QvPHwRHSkDttGu3c+IwbE5iL+qupBv3cYUzZSESPOqXjFYt48RvayqK8MRJJeSG7qlek0+AFPq9vvGjUkmvDAtWrtoR5QxiDXvJoqH64khy09fe5aZe+a4Uo+70AmRRQEgVXZboC3Wge0HShZIvGsq8KiukVlnrxoIF6SDgWhmoMq3/zkvR5vnfIYGXviky2u2N7Zz/Ex5GMwircg8b2sPB0F3YZne5ANl2erJAf11kv8rbvREEGKk5qVciObgejW4auo5tz+wOPvAoCkHGDQLHOTMWKvsKzF6jztX6s3bdFCGC82AqaCLH4o/OtJyiDnt+OEeRHyMRL8udu6ugbvU59q/2wyp5SWMYwbrYiAkdLT5XINja4ZjrgGZI=
  - secure: ho0r48iuAATKKeO1LGLYbJ61YRMj45RvQWWDhR4X55LGXdfUaO0NXGNBSk4+3po31uaCtlvShQVhnCaNYuF1TfEGK5646Y8dfQrDVPC1Yhq/dftKBxUJU+hkMb+HxRqL6QiZzMQcScvon7e4yRRmVGlM9MPNeqaecRLh7mKlgIgC7Rp1Lg4ijifpB8wk4l8zGTsVv8kNsTx8iVhh23vRFWKjVLLmYhb7kjanOdoDgiRfN4oyU5a8GHkz8VjMeVTutHO+O4P1UD46GJsLIX/w3aIzcJrWs10GPiirEAthzrcc+QJE2oI4eyoSCpJyRfL9iXDk3drpYx/JgtZqwywx25HLF81VyZXOUjuCaB9j7OBNx4Pp8ogF9CZxtlImWuZNYS/WCJvKx7Xc5i/fCPNaTflsNS1UyDAYautWnS4n1elc/Y4QIikVFcbCMD4nR+VPy24bG0gzgpCDUo3TyPFTMTrJLiMsQPCyD/4iV2z8/6hrnbUU+HDQTcgHozu0n4YwjxFrozx9Vc1FeGICDe9mu76YhT84cF6oqhtR1oJK1Mi49cJVZrDRusTRL6obpxV5+tbYKDCPdPmNZiteOs5bybIIXHb2iSKelGcD2cwcjEz2TSaSUnxoh6OWTfxbRfJ8spVACt2MSTay5y1Q1xCSWlr7ox1CWx4zMlnBOEaDjCc=
before_install:
- openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
  -in travis_rsa.enc -out travis_rsa -d
- rm travis_rsa.enc
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/id_rsa
- docker build -t akkien/docker-react -f Dockerfile.dev .
script:
- docker run -e CI=true akkien/docker-react npm run test
after_success:
- "./scripts/deploy.sh"
